siteUid: null
sortOrder: 1
template: wizard/verdiepingsdossiers/edit-verdiepingsdossier
uriParts:
  - bewerk-verdiepingsdossiers/
  -
    - number
    - \d+
uriPattern: 'bewerk-verdiepingsdossiers/<number:\d+>'
