fieldLayouts:
  2f5b7bc4-cc9f-4c7f-8577-6f9c3e38ecc2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 97b8ed85-6f4e-4563-af61-64fce08d3e61
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed35e35b-52d9-4544-8c98-a128bf571709 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e171afe-f13c-4bc2-aff8-9bf6f5f27d65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6edd9cc7-7f02-42eb-937e-8e242d90d712 # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dec44ae7-bada-46a3-8a13-0c56e420bfe0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1544c70f-6ecc-45b1-999e-41aa2e4a5825 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a902abb3-4d2f-40a7-950d-c0483fbf8559
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49088cc0-ab2b-42ec-a2a5-5a4d9c056bea # Sources
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c3697e5-2f08-4447-8576-89f0c379636a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8bb7f88e-5081-4282-9a21-b88973c4a703
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 82c18cfa-2186-41cc-b3a7-d8d4f28bcd33 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4889cbbe-b990-4ff2-9e68-0c72fbc30f72
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c9847ec4-05cf-49f9-ad55-b86d873568bf # Video's
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f72d1515-f541-4f6e-8ae7-9f8b32c50771
            userCondition: null
            warning: null
            width: 100
        name: Assets
        uid: 10b2e3c9-781b-4dd7-9736-acc84ae61dbd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 11488e99-48cf-4b89-ae9e-74a299337c18 # Category Thema
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31750ee7-22b6-40d5-9b92-0ae038cf2c3e
            userCondition: null
            warning: null
            width: 100
        name: category
        uid: a62d2a7b-40ec-4ea1-82a7-d8c1a0489b6b
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 9351f7fa-9eb7-49ad-b883-aaf9bbd832cf # Onderzoeksvragen
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
