fieldLayouts:
  55a490da-6b07-48e9-bbe5-bc3e4cf5118f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d54f3715-b71b-4436-9c50-b1d90e300ea0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed35e35b-52d9-4544-8c98-a128bf571709 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 856091f3-ce92-44c0-ab09-cd37c02a7b75
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3871e358-1e8f-4ba2-a077-76520af3d9f7 # Presentation Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0202dc9-4eb9-463a-b422-4f39200246b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6edd9cc7-7f02-42eb-937e-8e242d90d712 # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bd0bd9c-f570-4b7d-acd4-eeb62a1fa2a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5567d42c-050e-46f6-83dd-7e0e435629b4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 11488e99-48cf-4b89-ae9e-74a299337c18 # Category Thema
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53ed60c3-621e-4ded-b41b-8c0d52ba91da
            userCondition: null
            warning: null
            width: 100
        name: Category
        uid: ecc10b11-5e52-403f-8d0f-030f783cd96f
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: abee3b12-8257-485d-8573-c0268d3fd8b4 # Edu Escaperooms
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
