fieldLayouts:
  8ec28712-a52d-4f42-afab-508268b5556d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 77bb9e1e-6b51-459c-9a46-9cac604d9071
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 77e06622-3287-4d3f-8635-630ed811864a
        userCondition: null
handle: toegang
hasTitleField: false
name: Toegang
section: 99601d0e-e7cd-4c78-91b1-c36db3eadd99 # Toegang
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
