columnSuffix: null
contentColumnType: string
fieldGroup: 8de2ef2a-917d-4573-a731-2194990b8927 # Common
handle: categoryThemaSingle
instructions: null
name: 'Category Thema Single'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:299fffcc-2678-4d7b-a003-3c64178d734d' # Thema's
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
