dateModified: 1671633763
email:
  fromEmail: bjorvanh1@student.arteveldehs.be
  fromName: Zawia
  replyToEmail: bjorvanh1@student.arteveldehs.be
  template: ''
  transportSettings:
    encryptionMethod: none
    host: localhost
    password: ''
    port: '1025'
    timeout: '10'
    useAuthentication: '0'
    username: ''
  transportType: craft\mail\transportadapters\Smtp
fs:
  assets:
    hasUrls: false
    name: assets
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: null
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@web/assets'
meta:
  __names__:
    2de30c04-8173-4819-88a1-35c218877fa6: Artikelsoorten # Artikelsoorten
    5e5a77ad-3631-4235-b4a1-75dcf93f3eae: Icon # Icon
    8de2ef2a-917d-4573-a731-2194990b8927: Common # Common
    9b9ff0ef-f17a-4eaf-af42-ae98429b4950: Home # Home
    299fffcc-2678-4d7b-a003-3c64178d734d: 'Thema''s' # Thema's
    412bccbe-4151-4977-a605-8d9988b84eaa: Uploads # Uploads
    82064a65-72dc-4540-b424-e0692a2bbab1: Login
    a17e350d-daa8-4b8c-9140-a4668e8b40ef: Zawia # Zawia
    a781d844-0309-4579-81f5-a06f89fe8e0c: Login
    b2874c9f-b905-4009-8994-9088b3ed9c1e: Zawia # Zawia
    f6dcd4c6-ca82-4b5e-9934-70daee95ae93: Home # Home
plugins:
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: Zawia
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
