dateModified: 1673530092
email:
  fromEmail: bjorvanh1@student.arteveldehs.be
  fromName: Zawia
  replyToEmail: bjorvanh1@student.arteveldehs.be
  template: ''
  transportSettings:
    encryptionMethod: none
    host: localhost
    password: ''
    port: '1025'
    timeout: '10'
    useAuthentication: '0'
    username: ''
  transportType: craft\mail\transportadapters\Smtp
fs:
  assets:
    hasUrls: false
    name: assets
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: null
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@web/assets'
meta:
  __names__:
    0ee66cd5-5e81-452f-af33-df097cae35de: Soortid # Soortid
    2a0a7a45-546a-4b7a-9f90-8f841c8f6c44: Students # Students
    2de30c04-8173-4819-88a1-35c218877fa6: Artikelsoorten # Artikelsoorten
    3fffcb82-84de-4232-ba1a-3dfd2f0fc37d: 'Public Schema' # Public Schema
    5e5a77ad-3631-4235-b4a1-75dcf93f3eae: Icon # Icon
    5fdf1b3c-dbce-4c01-a2d9-59a8af774de3: Label # Label
    6c4f9f9f-a163-4996-96f5-f3f93649b5f6: Dossiers # Dossiers
    6edd9cc7-7f02-42eb-937e-8e242d90d712: Excerpt # Excerpt
    7dd22add-5475-42a6-93aa-1133b6797edc: Default # Default
    07f120b4-d3e2-4291-9995-a0524335a84e: 'Nieuw Artikel' # Nieuw Artikel
    8a8ed8be-4d9f-46b0-97b7-9787f89f7c99: Menu # Menu
    8be4852e-195f-4377-b09a-8f1a336b5ea6: 'Mijn Artikels' # Mijn Artikels
    8de2ef2a-917d-4573-a731-2194990b8927: Common # Common
    9b9ff0ef-f17a-4eaf-af42-ae98429b4950: Home # Home
    22d6c214-b6d3-4e35-a9ce-3bc5464a425a: 'Nieuw Artikel' # Nieuw Artikel
    32b71232-2401-44d6-bb54-ccdbd73bddad: Label # Label
    48dab1eb-6b6e-48f4-8227-82ba85f71da2: 'Mijn Artikels' # Mijn Artikels
    060c715f-7f84-45ab-b444-a372660505fa: Toegang # Toegang
    79c6387a-1ff2-4303-b7d5-5911c124ed85: 'Nieuw verdiepingsdossier' # Nieuw verdiepingsdossier
    82c18cfa-2186-41cc-b3a7-d8d4f28bcd33: Images # Images
    299fffcc-2678-4d7b-a003-3c64178d734d: 'Thema''s' # Thema's
    391bf39d-15d7-4339-894c-d2e5678179fd: 'Category Soort' # Category Soort
    412bccbe-4151-4977-a605-8d9988b84eaa: Uploads # Uploads
    1544c70f-6ecc-45b1-999e-41aa2e4a5825: Body # Body
    03861cc1-25e9-46f7-a3d0-3370e4881f5e: 'Bewerk themadossier' # Bewerk themadossier
    4481ba63-3323-44b0-a5f9-783bd08e3174: 'Bewerk themadossier' # Bewerk themadossier
    9143d726-4edc-42e6-bd7e-963498cf1eac: 'Bewerk Verdiepingsdossier' # Bewerk Verdiepingsdossier
    11488e99-48cf-4b89-ae9e-74a299337c18: 'Category Thema' # Category Thema
    58855ae7-51e0-4f88-9827-a90a6b8a70e5: 'Menu Items' # Menu Items
    82064a65-72dc-4540-b424-e0692a2bbab1: Login # Login
    99601d0e-e7cd-4c78-91b1-c36db3eadd99: Toegang # Toegang
    567278e8-d5ff-4fb3-8e1e-f4c7ed39dfc9: Verdiepingsdossiers # Verdiepingsdossiers
    30375302-41d5-48b8-9251-6f60f86596b9: Default # Default
    43850410-f9e9-4de1-aaad-423f84a0d5d8: 'Category Thema Single' # Category Thema Single
    a17e350d-daa8-4b8c-9140-a4668e8b40ef: Zawia # Zawia
    a781d844-0309-4579-81f5-a06f89fe8e0c: Login # Login
    b2874c9f-b905-4009-8994-9088b3ed9c1e: Zawia # Zawia
    b66552a3-1552-423b-b7fa-1db6b7a7876a: 'Nieuw Themadossier' # Nieuw Themadossier
    b5332235-c79e-406f-82c9-faa9fe658438: 'Bewerk Verdiepingsdossier' # Bewerk Verdiepingsdossier
    c5b2d6ec-5e5e-4fdf-8db7-b6c941319a67: Destination # Destination
    cd2017c1-ed0a-4f13-9c88-3d53c19c619a: 'Thema''s' # Thema's
    d0a7b5b2-2d89-4806-bd1d-6312e43b8f31: 'Soort Id' # Soort Id
    e022656e-6729-43b2-aa2f-31b66644c6e1: 'Nieuw Themadossier' # Nieuw Themadossier
    e4b10fcc-314a-4dbe-9c1e-71bbe01f9d07: Themadossiers # Themadossiers
    ec896c9b-91b7-46f8-a839-d56f4da0ae7f: Default # Default
    ed35e35b-52d9-4544-8c98-a128bf571709: Image # Image
    f2ce5aef-2433-48de-b247-ad9d2c1ccf34: Header # Header
    f6dcd4c6-ca82-4b5e-9934-70daee95ae93: Home # Home
    f626ace0-6e6e-4d03-9165-0d71e53485c5: 'Nieuw verdiepingsdossier' # Nieuw verdiepingsdossier
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: Zawia
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
