defaultPlacement: end
enableVersioning: true
handle: mijnArtikels
name: 'Mijn Artikels'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b2874c9f-b905-4009-8994-9088b3ed9c1e: # Zawia
    enabledByDefault: true
    hasUrls: true
    template: _pages/mijn-artikels
    uriFormat: mijn-artikels
type: single
