defaultPlacement: end
enableVersioning: true
handle: themadossiers
name: Themadossiers
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b2874c9f-b905-4009-8994-9088b3ed9c1e: # Zawia
    enabledByDefault: true
    hasUrls: true
    template: themadossiers/_entry
    uriFormat: 'themadossiers/{slug}'
structure:
  maxLevels: null
  uid: 51e7a364-57d6-41c2-bf1e-511575e1de24
type: structure
